# Generated by Django 3.2 on 2021-04-16 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='main_address',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_rank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.userrank'),
        ),
    ]
