# Generated by Django 3.2 on 2021-04-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userrank_previous_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrank',
            name='previous_payment',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
    ]
